title: Oodles 'n Oodles
theme: minima

# Add this navigation section if it doesnâ€™t exist
header_pages:
  - index.md
  - puppy_gallery.md
  - mumanddad.md
  - about.md
  



# Footer settings
footer:
  location: Melbourne Australia

